### PR TITLE
Feature/add members at creation

### PR DESCRIPTION
**Pull request by b97pla**
- In addition to the PI, additional members can be added to the delivery project at creation time
- PI and member email addresses are specified as a comma-separated list in the the projects email file. The first address in the list will be the PI.
- Some unit tests added

### CODE REVIEW

**Review by johandahlberg — CHANGES_REQUESTED** [review]
Looking at this, it made me think that perhaps it would be better to add an extra column to the csv file with extra members.

Since if I understand this correctly, we assume that the PI should always be first in the list, however I guess that is something that is quite easy to forget. This shouldn't be the case if we add an extra column with additional members (that can optionally be empty). What do you think about that?

**Comment by johandahlberg** [comment]
However, I should add that the above is just an idea, if you want to keep it this way I that that is perfectly fine to. :smile: Great work, and great work adding more tests to this! It's very much needed.

**Comment by b97pla** [comment]
Thanks for the suggestion @johandahlberg. I've updated the PR accordingly.

**Review by johandahlberg — APPROVED** [review]

**Comment by johandahlberg** [comment]
Nice! Merging.

**Pull request merged**
