### PR TITLE
Archive upload release

### PR DESCRIPTION
**Pull request by slohse**
**What problems does this PR solve?**
This PR adds archive upload and verify related workflows 

**How has the changes been tested?**
Monika validated the workflows on `mm-xart001` and `mm-xart002`

**Reasons for careful code review**
If any of the boxes below are checked, extra careful code review should be inititated.

  - [ ] This PR contains code that could remove data

### CODE REVIEW

**Review by johandahlberg — CHANGES_REQUESTED** [review]
This looks great! Good work. I have one comment, it appears to me that `actions/poll_status-archive.py` duplicates a lot of code from `actions/poll_status.py`. I've not looked at it that deeply, but I'm wondering if that is necessary?

**Comment by slohse** [comment]
Oh wow, good catch. That is 90% the same file.
From a first glance it seems like the only difference is better/more thorough error handling, so maybe we should just merge the changes into `poll_status.py`.

**Comment by johandahlberg** [comment]
Sounds like a good idea to me.

**Comment by johandahlberg** [comment]
LGTM. I think it would be worth investigating why the CI fails before merging, though.

**Comment by slohse** [comment]
Yeah, I don't get it really. It fails when installing Tornado via pip, saying 
> Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).

Yet, in the very beginning of the log we have 
```
$ python --version
Python 2.7.14
```

I was suspecting the python version in the venv to be different somehow, but I can't find any indication for that in the log

**Comment by slohse** [comment]
But that is indeed the case. I added a `python --version` in `utils/prepare_test_env.sh` and the [output](https://travis-ci.org/Molmed/arteria-packs/builds/362570013#L636) shows
```
Python 2.7.6
```

**Comment by johandahlberg** [comment]
I'm not sure, but maybe it is possible to specify a new python version for in the `.travis.yaml` file?

**Comment by slohse** [comment]
Okay, that fixed that. Now it fails because the mock does not implement the additional error handling we merged into `poll_status.py`. I'll have a look at that.

**Comment by slohse** [comment]
alright, that did it \o/

**Comment by johandahlberg** [comment]
I'm good with this. Does @monikaBrandt want to have a look as well?

**Review by johandahlberg — APPROVED** [review]

**Review by monikaBrandt — COMMENTED** [review]
There are some files included in this release that were not included in the validation. We need to figure out how to exclude these from the release. Apart from that everything looks good! Nice job!

Non-validated files:
actions/archive_missing_files_irma.yaml
actions/archive_remove.yaml
actions/archive_set_removable.yaml
actions/archive_upload_irma.yaml
actions/workflows/archive_missing_files_irma.yaml
actions/workflows/archive_remove.yaml
actions/workflows/archive_set_removable.yaml
actions/workflows/archive_upload_irma.yaml

**Comment by monikaBrandt** [comment]
Realized that this one "actions/workflows/ngi_uu_workflow.yaml" is not validated as well.

**Review by monikaBrandt — APPROVED** [review]
This looks good to me!

**Pull request merged**
