### PR TITLE
Rename workflows

### PR DESCRIPTION
**Pull request by matrulda**
**What problems does this PR solve?**
Adding the suffix `_workflow` to all workflows. The original idea was to just rename `archive_upload`, so that such workflows would be listed together with other workflows when tracing a runfolder/project, but I figured it made sense to rename all workflows to separate them from actions. This is of course up for debate. 

**How has the changes been tested?**
No tests. 

**Reasons for careful code review**
If any of the boxes below are checked, extra careful code review should be inititated.

  - [ ] This PR contains code that could remove data

### CODE REVIEW

**Comment by johandahlberg** [comment]
I do think that it makes sense to change them all. However, I'm wondering if we should maybe validate this somehow to make sure that we don't break anything?

**Comment by matrulda** [comment]
I was thinking that we at least could validate that the ngi_uu_workflow including archive_upload_workflow works as expected before deploying in production.

**Comment by johandahlberg** [comment]
Sounds good. Another way to verify it could possibly be to parse the files and make sure that all the things they point to exist. Should be fairly simple to write a script for that, that we could then include under our continuous integration.

**Comment by matrulda** [comment]
Great idea @johandahlberg ! I've started working on such script, will put it among the other scripts in  `snpseq_packs/scripts`.  Stay tuned.

**Review by sarek928 — COMMENTED** [review]
Looks good! I think it's a great idea to change the names in order to clarify the workflows.

**Comment by matrulda** [comment]
Ok, so I tried to validate this with a script, but it turned out to be more work than I anticipated, see #41 . From the implementation I was able to produce, it looks like this PR does not break anything. Given that + that we will validate that ngi_uu_workflow (including archive_upload) is working before making a new production release, I think it is safe to merge.

**Pull request merged**
