### PR TITLE
Force creation of symbolic link

### PR DESCRIPTION
**Pull request by matrulda**
**What problems does this PR solve?**
The create_lims_integration_links task would fail if a link already existed, this PR will solve this issue. 

**How has the changes been tested?**
No, but will be tested in the staging environment. 

**Reasons for careful code review**
If any of the boxes below are checked, extra careful code review should be inititated.

  - [ ] This PR contains code that could remove data

### CODE REVIEW

**Comment by slohse** [comment]
Looks good.
Just to make sure: what if the link exists, but pointed somewhere else? That is not a scenario we have to worry about, right?

**Comment by matrulda** [comment]
> Looks good.
> Just to make sure: what if the link exists, but pointed somewhere else? That is not a scenario we have to worry about, right?

I would say that our general "policy" in this workflow is that the most recent run should be the valid one, so I don't see any problem with overwriting, even if the former link pointed somewhere else (which should be very unlikely).

**Comment by slohse** [comment]
Right, that's what I thought.

**Review by slohse — APPROVED** [review]
All good then :)

**Pull request merged**
